version: "3" 
services: 
  app: 
    build: . 
    container_name: clean-arch
    entrypoint: ./.docker/entrypoint.sh
    # options: --privileged
    volumes:
      - .:/app/
    cap_add:
      - ALL
    ports: 
      - 8000:80